### PR TITLE
Improve assemblyscript part

### PR DESCRIPTION
**Pull request by MaxGraey**
Here just suggestion how you could improve your AssemblyScript code for better perf and more concise look.

### CODE REVIEW

**Comment by alankrantas** [comment]
Actually, the code was copied from a C++ version somewhere online. If you check the TinyGo project you'll see my JS and Go versions are basically the same. And I left the type annotation on to remind me how AssemblyScript works.

The goal of this repo is just some (preliminary) personal experiment of how to use wasm resources in web pages. AssemblyScript generates a JS wrapper so it actually looks easier to use than Go, although I don't know if it can process non-number types (can it? I'd like to know please).

So pardon me, but your changes are not really relevant right now. But thanks anyway. And I wish the best for your home country :)

**Comment by MaxGraey** [comment]
> AssemblyScript generates a JS wrapper so it actually looks easier to use than Go, although I don't know if it can process non-number types (can it? I'd like to know please).

Yes, binding generator can handle mush more types. See docs: https://www.assemblyscript.org/compiler.html#host-bindings

**Comment by MaxGraey** [comment]
Btw AS and TinyGo sources is not the same.
TinyGo has [this line](https://github.com/alankrantas/wasm_experiments/blob/main/tinygo-wasm/src/nqueens/nq.go#L15)
while AS [doesn't](https://github.com/alankrantas/wasm_experiments/blob/main/assemblyscript/assembly/index.ts#L4)
So results will different

**Comment by MaxGraey** [comment]
Also TinyGo operates uint8 and int32 as a result type while AS operates i32 and i64 as a result type

**Comment by alankrantas** [comment]
Thanks.

Go and JS/TS have their differences so the way to "initialize" the calculation are a bit different. But the core code are the same as always. And I can assure you the results are exactly the same because the TS version is essentially the JS version with AS type annotations.

**Comment by MaxGraey** [comment]
If you want portable AS/TS code you shoudn't use `i64`. Because this not TS/AS type (JS has only BigInt and Numbers). SO I'm not sure you preserve your goal keep everything JS-like in AS sources

**Pull request closed without merging**
